### ISSUE TITLE
JSON Error

### ISSUE THREAD

**Issue by tylersticka** [mattstein/alfred-quick-open-project-workflow#1] opened 2024-09-13 16:08 UTC
This looks awesome, @mattstein!

I installed the workflow and set the `SEARCH_PATHS` environment variable per instructions:

<img width="912" alt="Screenshot 2024-09-13 at 9 03 24 AM" src="https://github.com/user-attachments/assets/db96d956-9b4e-477a-a2ef-528ebda74bee">

But when I type `src` it says "Hang on..." for a moment and then peaces out to the default web search commands.

Looking at the workflow debugger, I do see an error:

```
[09:03:53.041] ERROR: Quick Open Project[Script Filter] JSON error: JSON text did not start with array or object and option to allow fragments not set. around line 1, column 0. in JSON:
Fatal error: Uncaught TypeError: Fuse\Fuse::searchLogical(): Argument #1 ($query) must be of type array, null given, called in /Users/tylersticka/Alfred Preferences/Alfred.alfredpreferences/workflows/user.workflow.DA9609C4-4068-410C-A509-DEE36CDBC7FA/vendor/loilo/fuse/src/Fuse.php on line 121 and defined in /Users/tylersticka/Alfred Preferences/Alfred.alfredpreferences/workflows/user.workflow.DA9609C4-4068-410C-A509-DEE36CDBC7FA/vendor/loilo/fuse/src/Fuse.php:173
Stack trace:
#0 /Users/tylersticka/Alfred Preferences/Alfred.alfredpreferences/workflows/user.workflow.DA9609C4-4068-410C-A509-DEE36CDBC7FA/vendor/loilo/fuse/src/Fuse.php(121): Fuse\Fuse->searchLogical(NULL)
#1 /Users/tylersticka/Alfred Preferences/Alfred.alfredpreferences/workflows/user.workflow.DA9609C4-4068-410C-A509-DEE36CDBC7FA/search.php(50): Fuse\Fuse->search(NULL)
#2 {main}
  thrown in /Users/tylersticka/Alfred Preferences/Alfred.alfredpreferences/workflows/user.workflow.DA9609C4-4068-410C-A509-DEE36CDBC7FA/vendor/loilo/fuse/src/Fuse.php on line 173
```

Any idea where I'm going wrong? 🤔  My PHP and workflow dev skills are rusty so I'm having trouble figuring out how best to troubleshoot. Happy to provide more info! (And obviously _no_ urgency, personal projects should be fun, I'll make do just fine! 🙂)

**Comment by mattstein** [comment] 2024-09-13 16:18
Oh well that’s no fun! Would you mind giving [this new release](https://github.com/mattstein/alfred-quick-open-project-workflow/releases/tag/v0.0.2) a shot?

**Comment by tylersticka** [comment] 2024-09-13 16:24
So now there's no error, but the output hasn't changed. But the debugger _does_ show items being found, but weirdly there's always a `null` result right after as well. 🤔 

Here's the debug log as I start typing `hello` (redacting some directory results that would dox my clients 😅)

```
[09:19:07.283] Quick Open Project[Script Filter] Queuing argument ''
[09:19:07.386] Quick Open Project[Script Filter] Script with argv '(null)' finished
[09:19:07.393] Quick Open Project[Script Filter] {"items":[]}
[09:19:23.958] Quick Open Project[Script Filter] Queuing argument ''
[09:19:24.098] Quick Open Project[Script Filter] Script with argv '(null)' finished
[09:19:24.103] Quick Open Project[Script Filter] {"items":[]}
[09:19:27.303] Quick Open Project[Script Filter] Queuing argument 'h'
[09:19:27.471] Quick Open Project[Script Filter] Script with argv '(null)' finished
[09:19:27.476] Quick Open Project[Script Filter] {"items":[]}
[09:19:28.016] Quick Open Project[Script Filter] Queuing argument 'he'
[09:19:28.078] Quick Open Project[Script Filter] Queuing argument 'hel'
[09:19:28.178] Quick Open Project[Script Filter] Script with argv '(null)' finished
[09:19:28.184] Quick Open Project[Script Filter] {"items":[{"arg":"\/Users\/tylersticka\/Repos\/REDACTED","icon":{"path":"\/Applications\/Visual Studio Code.app","type":"fileicon"},"mods":{"cmd":{"icon":{"path":"\/Applications\/PhpStorm.app","type":"fileicon"}},"shift":{"icon":{"path":"\/Applications\/iTerm.app","type":"fileicon"}},"ctrl":{"icon":{"path":"\/System\/Library\/CoreServices\/Finder.app","type":"fileicon"}}},"subtitle":"\/Users\/tylersticka\/Repos\/REDACTED","title":"REDACTED"},{"arg":"\/Users\/tylersticka\/Repos\/REDACTED","icon":{"path":"\/Applications\/Visual Studio Code.app","type":"fileicon"},"mods":{"cmd":{"icon":{"path":"\/Applications\/PhpStorm.app","type":"fileicon"}},"shift":{"icon":{"path":"\/Applications\/iTerm.app","type":"fileicon"}},"ctrl":{"icon":{"path":"\/System\/Library\/CoreServices\/Finder.app","type":"fileicon"}}},"subtitle":"\/Users\/tylersticka\/Repos\/REDACTED","title":"REDACTED"},{"arg":"\/Users\/tylersticka\/Repos\/REDACTED","icon":{"path":"\/Applications\/Visual Studio Code.app","type":"fileicon"},"mods":{"cmd":{"icon":{"path":"\/Applications\/PhpStorm.app","type":"fileicon"}},"shift":{"icon":{"path":"\/Applications\/iTerm.app","type":"fileicon"}},"ctrl":{"icon":{"path":"\/System\/Library\/CoreServices\/Finder.app","type":"fileicon"}}},"subtitle":"\/Users\/tylersticka\/Repos\/REDACTED","title":"REDACTED"},{"arg":"\/Users\/tylersticka\/Repos\/REDACTED","icon":{"path":"\/Applications\/Visual Studio Code.app","type":"fileicon"},"mods":{"cmd":{"icon":{"path":"\/Applications\/PhpStorm.app","type":"fileicon"}},"shift":{"icon":{"path":"\/Applications\/iTerm.app","type":"fileicon"}},"ctrl":{"icon":{"path":"\/System\/Library\/CoreServices\/Finder.app","type":"fileicon"}}},"subtitle":"\/Users\/tylersticka\/Repos\/REDACTED","title":"REDACTED"},{"arg":"\/Users\/tylersticka\/Repos\/REDACTED","icon":{"path":"\/Applications\/Visual Studio Code.app","type":"fileicon"},"mods":{"cmd":{"icon":{"path":"\/Applications\/PhpStorm.app","type":"fileicon"}},"shift":{"icon":{"path":"\/Applications\/iTerm.app","type":"fileicon"}},"ctrl":{"icon":{"path":"\/System\/Library\/CoreServices\/Finder.app","type":"fileicon"}}},"subtitle":"\/Users\/tylersticka\/Repos\/REDACTED","title":"REDACTED"}]}
[09:19:28.230] Quick Open Project[Script Filter] Queuing argument 'hell'
[09:19:28.345] Quick Open Project[Script Filter] Script with argv '(null)' finished
[09:19:28.351] Quick Open Project[Script Filter] {"items":[]}
[09:19:28.448] Quick Open Project[Script Filter] Queuing argument 'hello'
[09:19:28.489] Quick Open Project[Script Filter] Script with argv '(null)' finished
[09:19:28.495] Quick Open Project[Script Filter] {"items":[{"arg":"\/Users\/tylersticka\/Repos\/REDACTED","icon":{"path":"\/Applications\/Visual Studio Code.app","type":"fileicon"},"mods":{"cmd":{"icon":{"path":"\/Applications\/PhpStorm.app","type":"fileicon"}},"shift":{"icon":{"path":"\/Applications\/iTerm.app","type":"fileicon"}},"ctrl":{"icon":{"path":"\/System\/Library\/CoreServices\/Finder.app","type":"fileicon"}}},"subtitle":"\/Users\/tylersticka\/Repos\/REDACTED","title":"REDACTED"}]}
[09:19:28.570] Quick Open Project[Script Filter] Script with argv '(null)' finished
[09:19:28.575] Quick Open Project[Script Filter] {"items":[]}
```

**Comment by mattstein** [comment] 2024-09-13 16:35
Thanks for the info, and don’t feel any pressure to keep at this right now!

I just created [another release](https://github.com/mattstein/alfred-quick-open-project-workflow/releases/tag/v0.0.3) that may fix the problem, and if not will at least log some stuff I’m curious about.

You can switch the debugger to output more limited “Core Info” so we don’t have to risk doxxing your clients:

![Screen Shot 2024-09-13 at 09 32 22 AM@2x](https://github.com/user-attachments/assets/0b085ee0-d5fc-44b9-abeb-c638e2012788)

If something’s still weird, we should get some clues like this:

```
[09:32:16.798] Logging Started...
[09:32:37.051] STDERR: Quick Open Project[Script Filter] [Quick Open Project] 2024-09-13 09:32:37 PHP version: 8.3.11
[09:32:37.724] STDERR: Quick Open Project[Script Filter] [Quick Open Project] 2024-09-13 09:32:37 PHP version: 8.3.11
[Quick Open Project] 2024-09-13 09:32:37 Search glob: {/Users/mattstein/Projects}/*
[Quick Open Project] 2024-09-13 09:32:37 Matching results: 5
```

I’m not sure how the workflow keeps getting `null` when you’re providing an argument, and if it feels like I’m guessing it’s because I can’t reproduce that over here yet.

**Comment by tylersticka** [comment] 2024-09-13 19:49
@mattstein I think that fixed the main issue!

<img width="605" alt="Screenshot 2024-09-13 at 12 45 26 PM" src="https://github.com/user-attachments/assets/d49521c9-d5b7-4dc3-99e6-fbb21ab69c7d">

In case it helps diagnose whatever the issue was, here's the debugging output when it was successful as I typed `src tyler`:

```
[12:47:18.811] STDERR: Quick Open Project[Script Filter] [Quick Open Project] 2024-09-13 12:47:18 PHP version: 8.3.11
[12:47:20.617] STDERR: Quick Open Project[Script Filter] [Quick Open Project] 2024-09-13 12:47:20 PHP version: 8.3.11
[Quick Open Project] 2024-09-13 12:47:20 Search glob: {/Users/tylersticka/Repos}/*
[Quick Open Project] 2024-09-13 12:47:20 Matching results: 5
[12:47:21.118] STDERR: Quick Open Project[Script Filter] [Quick Open Project] 2024-09-13 12:47:21 PHP version: 8.3.11
[Quick Open Project] 2024-09-13 12:47:21 Search glob: {/Users/tylersticka/Repos}/*
[Quick Open Project] 2024-09-13 12:47:21 Matching results: 4
[12:47:21.470] STDERR: Quick Open Project[Script Filter] [Quick Open Project] 2024-09-13 12:47:21 PHP version: 8.3.11
[Quick Open Project] 2024-09-13 12:47:21 Search glob: {/Users/tylersticka/Repos}/*
[Quick Open Project] 2024-09-13 12:47:21 Matching results: 2
[12:47:21.909] STDERR: Quick Open Project[Script Filter] [Quick Open Project] 2024-09-13 12:47:21 PHP version: 8.3.11
[Quick Open Project] 2024-09-13 12:47:21 Search glob: {/Users/tylersticka/Repos}/*
[Quick Open Project] 2024-09-13 12:47:21 Matching results: 2
[12:47:21.998] STDERR: Quick Open Project[Script Filter] [Quick Open Project] 2024-09-13 12:47:21 PHP version: 8.3.11
[Quick Open Project] 2024-09-13 12:47:21 Search glob: {/Users/tylersticka/Repos}/*
[Quick Open Project] 2024-09-13 12:47:21 Matching results: 1
```

I don't know if this is intentional or not, but when I type `src`, no results are displayed. I have to type _some_ characters that result in a match to begin with. But as long as I remember some of the project folder name, it works.

**Comment by mattstein** [comment] 2024-09-13 19:53
Thanks for letting me know, @tylersticka! I’ll close this out and make an issue for showing all results without an argument. (I had it working that way before I started using this fuzzy search library, which doesn’t seem to be cool with an empty keyword.)

**Closed as completed** 2024-09-13 19:53 UTC
Labels: bug

**Comment by mattstein** [comment] 2024-09-13 20:23
...and [v0.0.4](https://github.com/mattstein/alfred-quick-open-project-workflow/releases/tag/v0.0.4) does that in case you want to subject yourself to yet another experiment!

**Comment by tylersticka** [comment] 2024-09-13 20:40
@mattstein That works great! You rock!!
